
unclassified:
  location:
    url: http://localhost:8080/
  locale:
    systemLocale: en
    ignoreAcceptLanguage: true

jenkins:
  systemMessage: "Jenkins FEOG"
  numExecutors: 1
  remotingSecurity:
    enabled: true
  # agentProtocols:
  #     - "JNLP4-connect"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_ADMIN_ID}
          password: ${JENKINS_ADMIN_PASSWORD}
  # authorizationStrategy:
  #     globalMatrix:
  #         grantedPermissions:
  #             - "Overall/Read:authenticated"
  #             - "Job/Read:authenticated"
  #             - "View/Read:authenticated"
  #             - "Overall/Administer:authenticated"
  crumbIssuer: "standard"
security:
  scriptApproval:
    approvedScriptHashes:
    - "SHA512:6c985b8810ea05eca5881306b0a87cadbef3030e480000f36fb0ade96b8a4e8bf746acfb28d41fdf1f5a4f06a00dd9cbbd8307687b8f2e274977f06b31524290"
jobs:
  - script: >
      job('Job_DSL_Seed') {
        scm {
          git {
            remote {
              url 'https://github.com/felix-orduz/jenkins.git'
            }
          }
        }
        steps {
          jobDsl {
            targets 'jobs/**/*.groovy'
          }
        }
      }
  - script: >
      pipelineJob('Simple job non critical task') {
        definition {
          cps {
            script('''
              pipeline {
                  agent any
                  stages {
                    stage('Test') {
                        steps {
                            script {
                                sh "echo this was executed on a spot instance"
                            }
                            sh 'sleep 30'
                            sh 'echo sleep is done'
                        }
                    }
                  }
              }'''.stripIndent())
              sandbox()
          }
        }
      }
  - script: >
      pipelineJob('Test 3') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url 'https://github.com/felix-orduz/jenkins.git'
                }
                branch 'main'
              }
              scriptPath 'JDSL/seed.jenkinsfile'
            }
          }
        }
      }

