
unclassified:
  location:
    url: http://localhost:8080/
  locale:
    systemLocale: en
    ignoreAcceptLanguage: true

jenkins:
  systemMessage: "Jenkins FEOG"
  numExecutors: 1
  remotingSecurity:
    enabled: true
  # agentProtocols:
  #     - "JNLP4-connect"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_ADMIN_ID}
          password: ${JENKINS_ADMIN_PASSWORD}
  # authorizationStrategy:
  #     globalMatrix:
  #         grantedPermissions:
  #             - "Overall/Read:authenticated"
  #             - "Job/Read:authenticated"
  #             - "View/Read:authenticated"
  #             - "Overall/Administer:authenticated"
  crumbIssuer: "standard"
security:
  scriptApproval:
    approvedScriptHashes:
    - "SHA512:6c985b8810ea05eca5881306b0a87cadbef3030e480000f36fb0ade96b8a4e8bf746acfb28d41fdf1f5a4f06a00dd9cbbd8307687b8f2e274977f06b31524290"
    - "SHA512:9a7026257fa63f3947cc0cc7d3db2bb0630cc723b458bbdd8c7b8c3dc05d5364a23c9ad2b3681a39e2ba42d71e2978c3839c8bd8b806ae2c835e2aea8d792d98"
    - "SHA512:c4d604f37e39120ac929538010fe560823bef0302daa332aec771a2527ae88b60f4be0306ef5ec204b9e801f574fd73c825fcc84eb4c224624d3555914cb4d97"
jobs:
  - script: >
      pipelineJob('Seed Job') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url 'https://github.com/felix-orduz/jenkins.git'
                }
                branch 'main'
              }
              scriptPath 'JDSL/seed.jenkinsfile'
            }
          }
        }
      }

